# Generated by Django 4.2 on 2023-04-08 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('image_path', models.CharField(default='.png', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leiloaoapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image_path', models.CharField(default='.png', max_length=255, verbose_name='Caminho da Imagem')),
                ('isSold', models.BooleanField(verbose_name='Artigo Vendido')),
                ('initialAsk', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bidStartDate', models.DateTimeField(verbose_name='Data Publicação')),
                ('bidEndDate', models.DateTimeField(verbose_name='Data Publicação')),
                ('lastBidDate', models.DateTimeField(verbose_name='Data Publicação')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bidder', to='leiloaoapp.appuser')),
                ('currentHighestBid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HighestBid', to='leiloaoapp.bid')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to='leiloaoapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WatchListLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AppUser', to='leiloaoapp.appuser')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WatchingSale', to='leiloaoapp.sale')),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BidSale', to='leiloaoapp.sale'),
        ),
    ]
