# Generated by Django 4.2 on 2023-04-30 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leiloaoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='image_path',
            field=models.CharField(default='.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bidder', to='leiloaoapp.appuser'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='isSold',
            field=models.BooleanField(default=False, verbose_name='Artigo Vendido'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='lastBidDate',
            field=models.DateTimeField(null=True, verbose_name='Data Publicação'),
        ),
    ]
