# Generated by Django 4.2 on 2023-05-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leiloaoapp', '0002_alter_appuser_image_path_alter_sale_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
